services:
  db:
    image: postgres:15-alpine
    container_name: consist-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consist_db
      # Указываем Postgres сохранять данные в подпапку (решает проблемы с правами на Windows)
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      # Проецируем папку из контейнера в реальную папку db_data в корне твоего проекта
      - ./db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: consist-backend-img
    container_name: consist-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/consist_db?schema=public&client_encoding=utf8"
      JWT_SECRET: "super-secret-key-for-consist"
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: consist-frontend-img
    container_name: consist-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend